version: "3.4"
x-restart-policy: &restart-policy
  restart: unless-stopped

services:
  database:
    <<: *restart-policy
    image: "postgres:12.2"
    environment:
      POSTGRES_DB: "root"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - "root-database:/var/lib/postgresql/data"
  redis:
    <<: *restart-policy
    image: "redis:7.4-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "root-redis:/var/lib/redis/data"
  ra-ffdecks:
    <<: *restart-policy
    ports:
      - "5000:5000"
    build: .
    depends_on:
      - database
    env_file:
      - .env.docker
    volumes:
      - "./app:/code/app"
  celery:
    <<: *restart-policy
    build: .
    depends_on:
      - redis
      - ra-ffdecks
    volumes:
      - "./app:/code/app"
      - "./migrations:/code/migrations"
    command: celery -A app.celery_worker worker -l INFO
    env_file:
      - .env.docker

volumes:
  root-database:
  root-redis: