version: "3.4"
x-restart-policy: &restart-policy
  restart: unless-stopped

services:
  database:
    <<: *restart-policy
    image: "postgres:12.2"
    environment:
      POSTGRES_DB: "root"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - "root-database:/var/lib/postgresql/data"
  ra-ffdecks:
    <<: *restart-policy
    ports:
      - "5000:5000"
    build: .
    depends_on:
      - database

volumes:
  root-database: