"""Update password lenght

Revision ID: 4416c7818e50
Revises:
Create Date: 2024-11-20 11:58:47.791433

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4416c7818e50"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=80),
            type_=sa.String(length=800),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.String(length=800),
            type_=sa.VARCHAR(length=80),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
